/* Create database */

CREATE DATABASE collection;

/* Create item table */

CREATE TABLE item (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  author VARCHAR,
  source VARCHAR,
  label VARCHAR,
  publish_date DATE NOT NULL,
  archived BOOLEAN
)

/* Create Music album talbe with item as father */

CREATE TABLE music_album (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  on_spotify BOOLEAN NOT NULL
) INHERITS (item);

/* Create genre table */

CREATE TABLE genre (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR
)

/* Create author table */

CREATE TABLE author (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  first_name VARCHAR,
  last_name VARCHAR
)

/* Alter table item to create relationship  */

ALTER TABLE item
ADD genre_id INT;

ALTER TABLE item
ADD author_id INT;

ALTER TABLE item
ADD FOREIGN KEY (genre_id) REFERENCES genre(id);

ALTER TABLE item
ADD FOREIGN KEY (author_id) REFERENCES author(id);

CREATE TABLE book (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(250),
    publish_date  DATE,
    publihser VARCHAR(250),
    cover_state VARCHAR(250),
    archived BOOLEAN,
    genre_id INT,
    author_id INT,
    label_id INT,
    FOREIGN KEY (genre_id) REFERENCES genre(id),
    FOREIGN KEY (author_id) REFERENCES author(id),
    FOREIGN KEY (label_id) REFERENCES label(id)
);

CREATE TABLE label (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(250),
    color VARCHAR(50)
);

CREATE TABLE game(
  id              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title           VARCHAR(255),
  publish_date    DATE,
  last_played_at  DATE,
  multiplayer     BOOLEAN,
  archived        BOOLEAN,
  author_id       INTEGER,
  genre_id        INTEGER,
  label_id        INTEGER,
  FOREIGN KEY (author_id) REFERENCES author(id),
  FOREIGN KEY (genre_id) REFERENCES genre(id),
  FOREIGN KEY (label_id) REFERENCES label(id)
);
